### ISSUE TITLE
Filter by type?

### ISSUE THREAD

**Issue by Ruriko** [esp10mm/HentaiFeedFilter#1]
Is there a way to filter the rss by type? like I only want doujinshi torrents

**Comment by esp10mm** [comment]
Hi , I just update the app, and you can filter by type now !
For example , try to subscribe following urls: 

```
http://hentaifeedfilter.herokuapp.com/?type=doujinshi
http://hentaifeedfilter.herokuapp.com/?type=doujinshi&&tags=chinese
http://hentaifeedfilter.herokuapp.com/?type=manga&&tags=Taishinkokuoh%20Anton
```

**Comment by Ruriko** [comment]
thanks for adding this feature! can you also make it work with artistcg & gamecg?

**Comment by esp10mm** [comment]
There is type name in item title from origin e-hentai rss feed and what my program do is filter item by its title.
You can reference <a href="http://xml.ehgt.org/ehg.xml">the origin source</a> to know artistcg type item will include "[Artist CG Sets]" in title.
So this will get what you want:

```
http://hentaifeedfilter.herokuapp.com/?type=Artist CG Sets
http://hentaifeedfilter.herokuapp.com/?type=Game CG Sets
```

By the way , the parameter is not  case sensitive.
